name: new_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1 
  flutter_svg: ^2.0.9
  flutter_iconly: ^1.0.2
  
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.15.3
  font_awesome_flutter: ^10.6.0

  cupertino_icons: ^1.0.6
  mask_text_input_formatter: ^2.7.0
  masked_text: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

assets:
  - lib/images/
  - lib/images/fb.png